{{- $name := printf "%s-db" .Release.Name }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "helpdesk.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if $existing }}
  root-password: {{ index $existing.data "root-password" }}
  password: {{ index $existing.data "password" }}
  {{- else }}
  root-password: {{ randAlphaNum 32 | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
